language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=tests
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros asdf install
  - ros -e '(ql:update-all-dists :prompt nil)'

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script: ros -e '(ql:quickload (list :cl-coveralls :split-sequence) :silent t)
                (coveralls:with-coveralls (:exclude (list "t"))
                  (ql:quickload :cl-yatlp-test)
                  (when (lisp-unit2:failed (lisp-unit2:with-summary ()
                                             (lisp-unit2:run-tests :package :lexer-tests)))
                    (uiop:quit 1)))'
