language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  - cl -l alexandria -l eager-future2 -e '(ql-util:without-prompting (ql:add-to-init-file))'
  - git clone git://github.com/rsauex/small-tests.git ~/lisp/small-tests

script:
  - cl -e '(ql:quickload :cl-yatlp)
           (ql:quickload :cl-yatlp-test)
           (unless (small-tests:run-tests)
             (uiop:quit 1))'
