language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_BRANCH=release
    - COVERAGE_EXCLUDE=tests
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script: ros -s cl-coveralls -s lisp-unit2 -e '
                (ql:quickload (list :cl-coveralls :split-sequence :lisp-unit2) :silent t)
                (coveralls:with-coveralls (:exclude (list "tests"))
                  (asdf:load-system :cl-yatlp/tests :verbose t)
                  (unless (asdf:perform (quote asdf:test-op) :cl-yatlp/tests)
                    (uiop:quit 1)))'
